
services:
  web:
    build: .
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: amakulbay
      POSTGRES_PASSWORD: Acsmat02!
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
