# Generated by Django 3.2.25 on 2024-10-12 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='created_at',
        ),
        migrations.AddField(
            model_name='post',
            name='image_url',
            field=models.URLField(null=True),
        ),
    ]
